"use client"

import { useState, useEffect, useMemo } from "react"
import { toast } from "sonner"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Users, Plus, Trash2, Edit, Search, Settings, Shuffle, Check, X } from "lucide-react"
import { AcademicStructureTree } from "@/components/academic/AcademicStructureTree"
import { useAuthentification } from "@/providers/authentification.provider"
import { useClasses } from "@/hooks/useClasses"
import { useAcademicStructure } from "@/hooks/useAcademicStructure"
import { serviceParametres } from "@/services/parametres.service"
import { serviceRepartition } from "@/services/repartition.service"
import type { Classe, ModeRepartition } from "@/types/models"
import type { TarificationTypeEcole } from "@/services/parametres.service"

// ...existing page content...
