"use client"

import { useEffect, useState } from "react"
import { ArrowLeft, BarChart3, ChevronLeft, ChevronRight, History, Loader2 } from "lucide-react"
import { useParams, useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { useAuthentification } from "@/providers/authentification.provider"
import { enseignantPortalService, type TeacherAttendanceHistory, type TeacherAttendanceStatistics, type TeacherClass } from "@/services/enseignant-portal.service"

const dateValue = (date: Date) => date.toISOString().slice(0, 10)
const initialFrom = () => { const d = new Date(); d.setDate(d.getDate() - 30); return dateValue(d) }
const today = () => dateValue(new Date())

export default function HistoriquePresencesEnseignantPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter()
  const { utilisateur, contexte, estEnCoursDeChargement } = useAuthentification()
  const [classes, setClasses] = useState<TeacherClass[]>([]); const [classId, setClassId] = useState("")
  const [from, setFrom] = useState(initialFrom); const [to, setTo] = useState(today)
  const [history, setHistory] = useState<TeacherAttendanceHistory | null>(null); const [stats, setStats] = useState<TeacherAttendanceStatistics | null>(null)
  const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const establishment = contexte?.establishments?.find((item) => item.id === id)

  useEffect(() => { if (!estEnCoursDeChargement && (!utilisateur || utilisateur.role !== "enseignant" || !establishment)) { router.replace("/enseignant"); return }; if (!establishment) return; enseignantPortalService.getClasses(id).then((rows) => { setClasses(rows); if (rows[0]) setClassId(rows[0].class_id) }).catch((e) => setError(e instanceof Error ? e.message : "Impossible de charger les classes.")) }, [id, establishment, estEnCoursDeChargement, router, utilisateur])
  useEffect(() => { if (!establishment || !classId || from > to) return; setLoading(true); setError(null); Promise.all([enseignantPortalService.getAttendanceHistory(id, page, 30, classId, undefined, from, to), enseignantPortalService.getAttendanceStatistics(id, from, to, classId)]).then(([h, s]) => { setHistory(h); setStats(s) }).catch((e) => setError(e instanceof Error ? e.message : "Impossible de charger l'historique.")).finally(() => setLoading(false)) }, [classId, establishment, from, id, page, to])
  const className = classes.find((c) => c.class_id === classId)?.class_name ?? "Classe"
  const statusLabel: Record<string, string> = { present: "Présent", absent: "Absent", late: "En retard", excused: "Excusé" }

  if (estEnCoursDeChargement || !utilisateur || !establishment) return <main className="min-h-screen bg-creme flex items-center justify-center"><Loader2 className="h-5 w-5 animate-spin" /></main>
  return <main className="min-h-screen bg-creme"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8">
    <header className="mb-6"><Button variant="ghost" size="sm" onClick={() => router.push(`/enseignant/etablissement/${id}/presences`)}><ArrowLeft className="mr-2 h-4 w-4" />Retour aux présences</Button><div className="mt-4"><p className="text-xs font-medium uppercase tracking-wide text-terre">Suivi pédagogique</p><h1 className="text-2xl font-semibold">Historique des présences</h1><p className="mt-1 text-sm text-muted-foreground">{establishment.name} · {className}</p></div></header>
    <Card className="mb-5"><CardContent className="grid gap-3 p-4 md:grid-cols-[1.3fr_1fr_1fr_auto]"><label className="text-sm font-medium">Classe<select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={classId} onChange={(e) => { setClassId(e.target.value); setPage(1) }}>{classes.map((c) => <option key={c.class_id} value={c.class_id}>{c.class_name} · {c.subject_name}</option>)}</select></label><label className="text-sm font-medium">Du<input type="date" className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={from} max={to} onChange={(e) => { setFrom(e.target.value); setPage(1) }} /></label><label className="text-sm font-medium">Au<input type="date" className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={to} min={from} max={today()} onChange={(e) => { setTo(e.target.value); setPage(1) }} /></label><div className="flex items-end"><Button variant="outline" onClick={() => { setFrom(initialFrom()); setTo(today()); setPage(1) }}>30 derniers jours</Button></div></CardContent></Card>
    {error && <div role="alert" className="mb-5 rounded-lg border p-4 text-sm text-rouge-terre">{error}</div>}
    {stats && <div className="mb-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat label="Taux de présence" value={`${stats.presence_rate}%`} /><Stat label="Enregistrements" value={stats.total} /><Stat label="Présents" value={stats.present} /><Stat label="Absents" value={stats.absent} /><Stat label="Retards" value={stats.late} /></div>}
    <div className="grid gap-5 lg:grid-cols-[1fr_1.8fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><BarChart3 className="h-4 w-4" />Répartition</CardTitle></CardHeader><CardContent>{stats ? <div className="space-y-4"><Bar label="Présents" value={stats.present} total={stats.total} /><Bar label="Absents" value={stats.absent} total={stats.total} /><Bar label="Retards" value={stats.late} total={stats.total} /><Bar label="Excusés" value={stats.excused} total={stats.total} /></div> : <p className="text-sm text-muted-foreground">Aucune donnée.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><History className="h-4 w-4" />Derniers enregistrements</CardTitle></CardHeader><CardContent className="p-0">{loading ? <div className="flex justify-center p-10"><Loader2 className="h-5 w-5 animate-spin" /></div> : !history?.data.length ? <p className="p-8 text-center text-sm text-muted-foreground">Aucun enregistrement sur cette période.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="border-b bg-muted/30 text-left text-muted-foreground"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Élève</th><th className="px-5 py-3">Statut</th><th className="px-5 py-3">Motif</th></tr></thead><tbody className="divide-y">{history.data.map((row) => <tr key={row.id}><td className="px-5 py-3 whitespace-nowrap">{row.attendance_date}</td><td className="px-5 py-3 font-medium">{row.last_name} {row.first_name}</td><td className="px-5 py-3">{statusLabel[row.status] ?? row.status}</td><td className="px-5 py-3 text-muted-foreground">{row.reason ?? "—"}</td></tr>)}</tbody></table></div>}
      {history && history.total_pages > 1 && <div className="flex items-center justify-between border-t px-5 py-3"><span className="text-xs text-muted-foreground">Page {history.page} sur {history.total_pages} · {history.total} enregistrement(s)</span><div className="flex gap-2"><Button variant="outline" size="icon" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}><ChevronLeft className="h-4 w-4" /></Button><Button variant="outline" size="icon" disabled={page >= history.total_pages} onClick={() => setPage((p) => p + 1)}><ChevronRight className="h-4 w-4" /></Button></div></div>}</CardContent></Card></div>
  </div></main>
}
function Stat({ label, value }: { label: string; value: number | string }) { return <div className="rounded-lg border bg-white p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div> }
function Bar({ label, value, total }: { label: string; value: number; total: number }) { const width = total ? Math.round(value / total * 100) : 0; return <div><div className="mb-1 flex justify-between text-sm"><span>{label}</span><span className="font-medium">{value} · {width}%</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-terre" style={{ width: `${width}%` }} /></div></div> }
