"use client"
import { useMemo, useState } from "react"
import { ChevronLeft, ChevronRight } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useParentPortal } from "@/hooks/use-parent-portal"
import { ParentPageHeader } from "@/components/parent/ParentPageHeader"
import { ParentChildSelect } from "@/components/parent/ParentChildSelect"
import { ParentEmptyState } from "@/components/parent/ParentEmptyState"
const days=["Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi"]
export default function ParentTimetable(){const{loading,error,refresh,children,timetable}=useParentPortal();const allowed=useMemo(()=>children.filter(c=>c.can_view_academic),[children]);const[childId,setChildId]=useState("tous"),[weekOffset,setWeekOffset]=useState(0);const classIds=new Set(allowed.filter(c=>childId==="tous"||c.id===childId).map(c=>c.class_id).filter(Boolean));const slots=timetable.filter(s=>classIds.has(s.class_id));return <div className="space-y-6"><ParentPageHeader eyebrow="Organisation" title="Emploi du temps" description="Consultez l’horaire scolaire de vos enfants." onRefresh={()=>void refresh()} refreshing={loading}/>{error&&<div className="border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{!loading&&allowed.length===0?<ParentEmptyState title="Emploi du temps non disponible" description="Votre compte n’a pas actuellement l’autorisation de consulter les cours."/>:<><div className="flex flex-col gap-3 border-b border-terre/10 pb-3 sm:flex-row sm:items-center sm:justify-between"><ParentChildSelect children={allowed} value={childId} onChange={setChildId}/><div className="flex items-center gap-1"><Button variant="ghost" size="icon" onClick={()=>setWeekOffset(x=>x-1)}><ChevronLeft className="h-4 w-4"/></Button><button className="px-3 text-sm font-medium text-terre" onClick={()=>setWeekOffset(0)}>{weekOffset===0?"Cette semaine":weekOffset>0?"Semaine suivante":"Semaine précédente"}</button><Button variant="ghost" size="icon" onClick={()=>setWeekOffset(x=>x+1)}><ChevronRight className="h-4 w-4"/></Button></div></div><div className="overflow-x-auto border border-terre/10 bg-papier"><div className="grid min-w-[900px] grid-cols-6 divide-x divide-terre/10">{days.map((day,i)=>{const items=slots.filter(s=>s.day_of_week===i+1);return <div key={day} className="min-h-[420px]"><div className="border-b border-terre/10 bg-creme px-3 py-3 text-center text-sm font-semibold text-terre">{day}</div><div className="space-y-2 p-3">{items.map(s=><div key={s.id} className="border-l-2 border-terre px-3 py-2"><p className="font-medium text-terre">{s.subject}</p><p className="text-xs text-pierre">{s.starts_at.slice(0,5)} – {s.ends_at.slice(0,5)}{s.room?" · "+s.room:""}</p></div>)}{items.length===0&&<p className="text-xs text-pierre">Aucun cours.</p>}</div></div>})}</div></div></>}</div>}