"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { LayoutDashboard, Users, FileText, UserX, CreditCard, Bell, MessageSquare, Calendar, LogOut, Menu, X, LifeBuoy } from "lucide-react"
import { useState } from "react"
import { Button } from "@/components/ui/button"
import { useAuthentification } from "@/providers/authentification.provider"
import { serviceParents } from "@/services/parents.service"
import { cn } from "@/lib/utils"

const liens=[{href:"/parents/tableau-bord",label:"Tableau de bord",icon:LayoutDashboard},{href:"/parents/enfants",label:"Mes enfants",icon:Users},{href:"/parents/notes",label:"Notes & bulletins",icon:FileText},{href:"/parents/absences",label:"Absences",icon:UserX},{href:"/parents/paiements",label:"Paiements",icon:CreditCard},{href:"/parents/notifications",label:"Notifications",icon:Bell,badge:"notifs"},{href:"/parents/messages",label:"Messages",icon:MessageSquare,badge:"msgs"},{href:"/parents/evenements",label:"Événements",icon:Calendar},{href:"/parents/service-technique",label:"Service technique",icon:LifeBuoy}]
export function ParentNav(){const pathname=usePathname();const {utilisateur,deconnecter}=useAuthentification();const [mobileOpen,setMobileOpen]=useState(false);const notifs=serviceParents.compterNotificationsNonLues();const msgs=serviceParents.compterMessagesNonLus();const NavLinks=({onNavigate}:{onNavigate?:()=>void})=><nav className="flex flex-col gap-1">{liens.map(({href,label,icon:Icon,badge})=>{const actif=pathname===href||pathname?.startsWith(href+"/");const count=badge==="notifs"?notifs:badge==="msgs"?msgs:0;return <Link key={href} href={href} onClick={onNavigate} className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-colors",actif?"bg-terre text-white shadow-soft":"text-pierre hover:bg-terre-soft hover:text-terre")}><Icon className="h-4 w-4 shrink-0"/><span className="flex-1">{label}</span>{count>0&&<span className={cn("min-w-[1.25rem] rounded-full px-1.5 py-0.5 text-center text-xs font-semibold",actif?"bg-white/20 text-white":"bg-soleil text-white")}>{count}</span>}</Link>})}</nav>;return <><div className="sticky top-0 z-30 flex items-center justify-between border-b border-terre/10 bg-papier/95 px-4 py-3 backdrop-blur lg:hidden"><div><p className="text-sm font-bold text-terre">Espace Parents</p><p className="text-xs text-pierre">{utilisateur?.nomUtilisateur??"Parent"}</p></div><Button variant="ghost" size="icon" onClick={()=>setMobileOpen(o=>!o)}>{mobileOpen?<X className="h-5 w-5"/>:<Menu className="h-5 w-5"/>}</Button></div>{mobileOpen&&<div className="fixed inset-0 z-40 bg-encre/30 lg:hidden" onClick={()=>setMobileOpen(false)}><div className="absolute left-0 top-0 flex h-full w-72 flex-col bg-papier p-4 shadow-soft" onClick={e=>e.stopPropagation()}><p className="mb-4 text-lg font-bold text-terre">Menu</p><NavLinks onNavigate={()=>setMobileOpen(false)}/><div className="mt-auto pt-4"><Button variant="outline" className="w-full rounded-xl" onClick={()=>deconnecter()}><LogOut className="mr-2 h-4 w-4"/>Déconnexion</Button></div></div></div>}<aside className="fixed left-0 top-0 z-20 hidden h-screen w-64 flex-col border-r border-terre/10 bg-papier px-4 py-6 lg:flex"><div className="mb-8 px-2"><p className="text-xs font-semibold uppercase tracking-wide text-terre">Scolarité</p><h1 className="text-xl font-bold text-terre">Espace Parents</h1><p className="mt-1 truncate text-sm text-pierre">{utilisateur?.nomUtilisateur??"Parent connecté"}</p></div><div className="flex-1 overflow-y-auto"><NavLinks/></div><Button variant="outline" className="mt-4 w-full rounded-xl" onClick={()=>deconnecter()}><LogOut className="mr-2 h-4 w-4"/>Déconnexion</Button></aside></>}
