"use client"

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react"
import { useParams, useRouter, useSearchParams } from "next/navigation"
import { ArrowLeft, Building2, CheckCircle2, Copy, Edit3, Loader2, Power, RefreshCcw, Shield, Trash2, UserCog, UserPlus, Users, X, XCircle, CreditCard, LifeBuoy, Info } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { supabaseBrowser } from "@/lib/supabase/client"

type Overview = { establishment_id: string; establishment_name: string; establishment_code: string; establishment_status: "active" | "inactive"; students_count: number; staff_count: number; classes_count: number; admins_count: number; plan_name: string | null; subscription_status: "active" | "expired" | "suspended" | null; starts_at: string | null; ends_at: string | null; max_students: number | null; max_staff: number | null; max_classes: number | null; max_admins: number | null }
type Member = { member_id: string; user_id: string; role: string; active: boolean; first_name: string | null; last_name: string | null; phone: string | null; avatar_url: string | null; email: string | null }
type Tab = "information" | "utilisateurs" | "personnel" | "abonnement"
const roleLabels: Record<string, string> = { owner: "Super administrateur", admin: "Administrateur", administrator: "Administrateur", direction: "Direction", teacher: "Enseignant", accountant: "Comptable", staff: "Personnel" }

export default function Page() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const searchParams = useSearchParams()
  const [overview, setOverview] = useState<Overview | null>(null); const [members, setMembers] = useState<Member[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState(false)
  const [editing, setEditing] = useState(searchParams.get("action") === "edit"); const [deleteConfirm, setDeleteConfirm] = useState(searchParams.get("action") === "delete"); const [adminModal, setAdminModal] = useState(searchParams.get("action") === "admin");
  const [name, setName] = useState(""); const [error, setError] = useState<string | null>(null); const [activeTab, setActiveTab] = useState<Tab>("information")
  const [adminForm, setAdminForm] = useState({ first_name: "", last_name: "", email: "", password: "" }); const [adminSaving, setAdminSaving] = useState(false); const [credentials, setCredentials] = useState<{ email: string; password: string } | null>(null)

  const load = useCallback(async () => { setLoading(true); setError(null); const [o, m] = await Promise.all([supabaseBrowser.rpc("platform_admin_establishment_overview", { p_establishment_id: id }), supabaseBrowser.rpc("get_establishment_members", { p_establishment_id: id })]); if (o.error) setError(o.error.message); const row = (o.data?.[0] ?? null) as Overview | null; setOverview(row); setName(row?.establishment_name ?? ""); setMembers((m.data ?? []) as Member[]); if (m.error && !o.error) setError(m.error.message); setLoading(false) }, [id])
  useEffect(() => { void load() }, [load])

  const updateName = async () => { if (!name.trim() || name.trim() === overview?.establishment_name) { setEditing(false); return } setSaving(true); setError(null); const { error: e } = await supabaseBrowser.rpc("platform_admin_update_establishment", { p_establishment_id: id, p_name: name.trim() }); if (e) setError(e.message); else setEditing(false); setSaving(false); await load() }
  const toggleStatus = async () => { if (!overview) return; setSaving(true); setError(null); const { error: e } = await supabaseBrowser.rpc("set_establishment_status", { p_establishment_id: id, p_status: overview.establishment_status === "active" ? "inactive" : "active" }); if (e) setError(e.message); setSaving(false); await load() }
  const toggleMemberActive = async (member: Member) => { setError(null); const { error: e } = await supabaseBrowser.rpc("platform_admin_set_member_active", { p_member_id: member.member_id, p_active: !member.active }); if (e) setError(e.message); await load() }
  const removeMember = async (member: Member) => { if (member.role === "owner") return; if (!window.confirm(`Retirer ${member.first_name ?? "cet utilisateur"} de l'établissement ?`)) return; setError(null); const { error: e } = await supabaseBrowser.rpc("remove_establishment_member", { p_member_id: member.member_id }); if (e) setError(e.message); await load() }
  const deleteEstablishment = async () => { setDeleting(true); setError(null); const { error: e } = await supabaseBrowser.rpc("platform_admin_delete_establishment", { p_establishment_id: id }); if (e) { setError(e.message); setDeleting(false); setDeleteConfirm(false); return } router.replace("/admin/etablissements") }
  const createSuperAdmin = async () => { setAdminSaving(true); setError(null); setCredentials(null); const { data, error: e } = await supabaseBrowser.functions.invoke("create-establishment-super-admin", { body: { establishment_id: id, ...adminForm } }); if (e) { setError(e.message); setAdminSaving(false); return } if (data?.error) { setError(data.error); setAdminSaving(false); return } setCredentials({ email: data.email, password: data.temporary_password }); setAdminForm({ first_name: "", last_name: "", email: "", password: "" }); await load(); setAdminSaving(false) }

  const personnel = useMemo(() => members.filter(m => ["owner", "admin", "administrator", "direction", "teacher", "accountant", "staff"].includes(m.role)), [members])

  if (loading) return <div className="mx-auto flex min-h-[50vh] max-w-7xl items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>
  if (!overview) return <div className="mx-auto max-w-3xl space-y-4"><Button variant="ghost" onClick={() => router.push("/admin/etablissements")}><ArrowLeft className="mr-2 h-4 w-4" />Retour</Button><Card><CardContent className="p-8 text-center"><XCircle className="mx-auto mb-3 h-10 w-10 text-destructive" /><p className="font-semibold">Établissement introuvable</p><p className="mt-1 text-sm text-muted-foreground">Vous n'avez peut-être pas les droits nécessaires.</p></CardContent></Card></div>
  const initials = overview.establishment_name.split(" ").map(p => p[0]).join("").slice(0, 2).toUpperCase()

  const tabs: { id: Tab; label: string; icon: typeof Info }[] = [
    { id: "information", label: "Informations", icon: Info },
    { id: "utilisateurs", label: "Utilisateurs", icon: Users },
    { id: "personnel", label: "Personnel", icon: UserCog },
    { id: "abonnement", label: "Abonnement", icon: CreditCard },
  ]

  return <div className="mx-auto max-w-7xl space-y-6 pb-10">
    <div className="flex flex-wrap items-center justify-between gap-3">
      <Button variant="ghost" onClick={() => router.push("/admin/etablissements")}><ArrowLeft className="mr-2 h-4 w-4" />Établissements</Button>
      <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void load()}><RefreshCcw className="mr-2 h-4 w-4" />Actualiser</Button><Button variant="outline" onClick={() => setAdminModal(true)}><UserPlus className="mr-2 h-4 w-4" />Super administrateur</Button><Button variant="destructive" onClick={() => setDeleteConfirm(true)}><Trash2 className="mr-2 h-4 w-4" />Supprimer</Button></div>
    </div>
    {error && <div className="rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}

    <Card className="overflow-hidden">
      <div className="border-b bg-primary/[0.04] p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-primary text-lg font-bold text-primary-foreground">{initials || <Building2 className="h-6 w-6" />}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2">{editing ? <div className="flex flex-wrap items-center gap-2"><Input value={name} onChange={e => setName(e.target.value)} className="max-w-sm" autoFocus /><Button size="sm" onClick={() => void updateName()} disabled={saving}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : "Enregistrer"}</Button><Button size="sm" variant="ghost" onClick={() => { setName(overview.establishment_name); setEditing(false) }}>Annuler</Button></div> : <><h1 className="text-2xl font-bold tracking-tight">{overview.establishment_name}</h1><Button size="icon" variant="ghost" onClick={() => setEditing(true)} aria-label="Modifier le nom"><Edit3 className="h-4 w-4" /></Button></>}</div><p className="mt-1 font-mono text-sm text-muted-foreground">{overview.establishment_code}</p><div className="mt-3 flex flex-wrap items-center gap-2 text-sm"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 font-medium ${overview.establishment_status === "active" ? "bg-emerald-100 text-emerald-700" : "bg-muted text-muted-foreground"}`}>{overview.establishment_status === "active" ? <CheckCircle2 className="h-3.5 w-3.5" /> : <XCircle className="h-3.5 w-3.5" />}{overview.establishment_status === "active" ? "Actif" : "Suspendu"}</span>{overview.plan_name && <span className="rounded-full bg-background px-2.5 py-1 text-muted-foreground">Plan : {overview.plan_name}</span>}</div></div></div><Button variant={overview.establishment_status === "active" ? "destructive" : "default"} onClick={() => void toggleStatus()} disabled={saving}>{overview.establishment_status === "active" ? <Power className="mr-2 h-4 w-4" /> : <RefreshCcw className="mr-2 h-4 w-4" />}{overview.establishment_status === "active" ? "Suspendre" : "Réactiver"}</Button></div></div>
      <div className="border-b bg-background px-4 sm:px-6"><div className="flex gap-1 overflow-x-auto" role="tablist" aria-label="Sections de l'établissement">{tabs.map(({ id: tabId, label, icon: Icon }) => <button key={tabId} type="button" role="tab" aria-selected={activeTab === tabId} onClick={() => setActiveTab(tabId)} className={`flex shrink-0 items-center gap-2 border-b-2 px-3 py-4 text-sm font-medium transition-colors ${activeTab === tabId ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:border-border hover:text-foreground"}`}><Icon className="h-4 w-4" />{label}{tabId === "utilisateurs" && <span className="rounded-full bg-muted px-2 py-0.5 text-xs">{members.length}</span>}{tabId === "personnel" && <span className="rounded-full bg-muted px-2 py-0.5 text-xs">{personnel.length}</span>}</button>)}</div></div>
    </Card>

    {activeTab === "information" && <section className="space-y-6">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<Users className="h-4 w-4" />} label="Élèves" value={overview.students_count} limit={overview.max_students} /><Stat icon={<UserCog className="h-4 w-4" />} label="Personnel" value={overview.staff_count} limit={overview.max_staff} /><Stat icon={<Building2 className="h-4 w-4" />} label="Classes" value={overview.classes_count} limit={overview.max_classes} /><Stat icon={<Shield className="h-4 w-4" />} label="Administrateurs" value={overview.admins_count} limit={overview.max_admins} /></div>
      <Card><CardHeader><CardTitle>Informations de l'établissement</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><InfoRow label="Nom" value={overview.establishment_name} /><InfoRow label="Code établissement" value={overview.establishment_code} mono /><InfoRow label="Statut" value={overview.establishment_status === "active" ? "Actif" : "Suspendu"} /><InfoRow label="Comptes utilisateurs" value={`${members.length}`} /><InfoRow label="Élèves" value={`${overview.students_count}`} /><InfoRow label="Personnel" value={`${overview.staff_count}`} /><InfoRow label="Classes" value={`${overview.classes_count}`} /></CardContent></Card>
    </section>}

    {activeTab === "utilisateurs" && <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Comptes utilisateurs</CardTitle><p className="mt-1 text-sm text-muted-foreground">Tous les comptes pouvant se connecter à cet établissement.</p></div><Button onClick={() => setAdminModal(true)}><UserPlus className="mr-2 h-4 w-4" />Créer le super administrateur</Button></div></CardHeader><CardContent className="p-0">{members.length === 0 ? <EmptyUsers onCreate={() => setAdminModal(true)} /> : <div className="divide-y">{members.map(member => <MemberRow key={member.member_id} member={member} onToggle={() => void toggleMemberActive(member)} onRemove={() => void removeMember(member)} />)}</div>}</CardContent></Card>}

    {activeTab === "personnel" && <Card><CardHeader><div><CardTitle>Personnel de l'établissement</CardTitle><p className="mt-1 text-sm text-muted-foreground">Vue de contrôle des comptes du personnel rattachés à cet établissement.</p></div></CardHeader><CardContent className="p-0">{personnel.length === 0 ? <div className="p-10 text-center text-sm text-muted-foreground">Aucun compte du personnel rattaché.</div> : <div className="divide-y">{personnel.map(member => <MemberRow key={member.member_id} member={member} onToggle={() => void toggleMemberActive(member)} onRemove={() => void removeMember(member)} />)}</div>}</CardContent></Card>}

    {activeTab === "abonnement" && <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><Card><CardHeader><CardTitle>Abonnement</CardTitle></CardHeader><CardContent className="space-y-4"><InfoRow label="Statut" value={overview.subscription_status ? ({ active: "Actif", expired: "Expiré", suspended: "Suspendu" } as Record<string, string>)[overview.subscription_status] : "Non configuré"} /><InfoRow label="Plan" value={overview.plan_name || "—"} /><InfoRow label="Date de début" value={overview.starts_at ? new Date(overview.starts_at).toLocaleDateString("fr-FR") : "—"} /><InfoRow label="Date de fin" value={overview.ends_at ? new Date(overview.ends_at).toLocaleDateString("fr-FR") : "—"} /><div className="pt-2"><Button className="w-full" onClick={() => router.push(`/admin/abonnements?establishment=${id}`)}><CreditCard className="mr-2 h-4 w-4" />Gérer l'abonnement</Button></div></CardContent></Card><Card><CardHeader><CardTitle>Limites du plan</CardTitle></CardHeader><CardContent className="space-y-3"><InfoRow label="Élèves" value={overview.max_students != null ? `${overview.max_students}` : "Illimité / non défini"} /><InfoRow label="Personnel" value={overview.max_staff != null ? `${overview.max_staff}` : "Illimité / non défini"} /><InfoRow label="Classes" value={overview.max_classes != null ? `${overview.max_classes}` : "Illimité / non défini"} /><InfoRow label="Administrateurs" value={overview.max_admins != null ? `${overview.max_admins}` : "Illimité / non défini"} /></CardContent></Card></div>}

    <div className="flex justify-end"><Button variant="outline" onClick={() => router.push("/admin/service-technique")}><LifeBuoy className="mr-2 h-4 w-4" />Service technique</Button></div>

    {adminModal && <Modal title="Créer le super administrateur" onClose={() => { if (!adminSaving) setAdminModal(false) }}><p className="mb-5 text-sm text-muted-foreground">Ce compte sera rattaché exclusivement à <strong>{overview.establishment_name}</strong> et recevra le rôle Super administrateur.</p>{credentials ? <div className="space-y-4"><div className="rounded-lg border bg-muted/40 p-4"><p className="text-sm font-medium">Compte créé avec succès</p><div className="mt-3 space-y-2 text-sm"><Credential label="E-mail" value={credentials.email} /><Credential label="Mot de passe" value={credentials.password} /></div></div><p className="text-xs text-muted-foreground">Conservez ces identifiants de manière sécurisée. Le mot de passe n'est affiché ici qu'après la création.</p><Button className="w-full" onClick={() => setAdminModal(false)}>Terminer</Button></div> : <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Prénom" value={adminForm.first_name} onChange={v => setAdminForm(f => ({ ...f, first_name: v }))} /><Field label="Nom" value={adminForm.last_name} onChange={v => setAdminForm(f => ({ ...f, last_name: v }))} /></div><Field label="E-mail de connexion" type="email" value={adminForm.email} onChange={v => setAdminForm(f => ({ ...f, email: v }))} /><Field label="Mot de passe" type="password" placeholder="Laisser vide pour générer automatiquement" value={adminForm.password} onChange={v => setAdminForm(f => ({ ...f, password: v }))} /><Button className="w-full" onClick={() => void createSuperAdmin()} disabled={adminSaving || !adminForm.first_name.trim() || !adminForm.last_name.trim() || !adminForm.email.trim()}>{adminSaving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <UserPlus className="mr-2 h-4 w-4" />}Créer le compte</Button></div>}</Modal>}
    {deleteConfirm && <Modal title="Supprimer cet établissement ?" onClose={() => setDeleteConfirm(false)}><p className="text-sm text-muted-foreground">Cette action est irréversible. Toutes les données rattachées à <strong>{overview.establishment_name}</strong> seront supprimées.</p><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setDeleteConfirm(false)} disabled={deleting}>Annuler</Button><Button variant="destructive" onClick={() => void deleteEstablishment()} disabled={deleting}>{deleting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Trash2 className="mr-2 h-4 w-4" />}Supprimer définitivement</Button></div></Modal>}
  </div>
}

function Stat({ icon, label, value, limit }: { icon: ReactNode; label: string; value: number; limit: number | null }) { return <div className="rounded-xl border bg-background p-4"><div className="flex items-center gap-2 text-sm text-muted-foreground">{icon}{label}</div><p className="mt-2 text-2xl font-bold">{value}{limit != null && <span className="text-sm font-normal text-muted-foreground"> / {limit}</span>}</p></div> }
function InfoRow({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="flex items-center justify-between gap-4 border-b py-2 last:border-0"><span className="text-sm text-muted-foreground">{label}</span><span className={`text-right text-sm font-medium ${mono ? "font-mono" : ""}`}>{value}</span></div> }
function MemberRow({ member, onToggle, onRemove }: { member: Member; onToggle: () => void; onRemove: () => void }) { return <div className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-semibold">{`${member.first_name?.[0] ?? ""}${member.last_name?.[0] ?? ""}`.toUpperCase() || "U"}</div><div className="min-w-0"><p className="truncate font-medium">{[member.first_name, member.last_name].filter(Boolean).join(" ") || "Utilisateur"}</p><p className="truncate text-xs text-muted-foreground">{member.email || "E-mail non disponible"}</p><p className="text-xs text-muted-foreground">{member.phone || "Aucun téléphone"}</p></div></div><div className="flex flex-wrap items-center justify-end gap-2"><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-medium">{roleLabels[member.role] ?? member.role}</span><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${member.active ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700"}`}>{member.active ? "Actif" : "Désactivé"}</span><Button size="sm" variant={member.active ? "outline" : "default"} onClick={onToggle}>{member.active ? "Désactiver" : "Réactiver"}</Button>{member.role !== "owner" && <Button size="icon" variant="ghost" className="text-destructive hover:text-destructive" onClick={onRemove} aria-label="Retirer"><Trash2 className="h-4 w-4" /></Button>}</div></div> }
function EmptyUsers({ onCreate }: { onCreate: () => void }) { return <div className="p-10 text-center"><Users className="mx-auto mb-3 h-9 w-9 text-muted-foreground" /><p className="font-medium">Aucun compte utilisateur</p><p className="mt-1 text-sm text-muted-foreground">Créez le premier compte, celui-ci sera le super administrateur de l'établissement.</p><Button className="mt-4" onClick={onCreate}><UserPlus className="mr-2 h-4 w-4" />Créer le super administrateur</Button></div> }
function Field({ label, value, onChange, type = "text", placeholder = "" }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <label className="block space-y-1.5"><span className="text-sm font-medium">{label}</span><Input type={type} value={value} placeholder={placeholder} onChange={e => onChange(e.target.value)} /></label> }
function Credential({ label, value }: { label: string; value: string }) { const copy = () => void navigator.clipboard?.writeText(value); return <div className="flex items-center justify-between gap-3 rounded-md border bg-background px-3 py-2"><div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className="truncate font-mono">{value}</p></div><Button size="icon" variant="ghost" onClick={copy} aria-label={`Copier ${label}`}><Copy className="h-4 w-4" /></Button></div> }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-[100] flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-label={title}><div className="fixed inset-0 bg-black/65 backdrop-blur-[3px]" onClick={onClose} /><div className="relative z-[100] w-full max-w-lg overflow-hidden rounded-xl border border-border bg-background text-foreground shadow-2xl"><div className="flex items-center justify-between border-b bg-background px-6 py-4"><h2 className="text-lg font-semibold">{title}</h2><Button size="icon" variant="ghost" onClick={onClose} aria-label="Fermer"><X className="h-4 w-4" /></Button></div><div className="bg-background px-6 py-5">{children}</div></div></div> }
