"use client"

import { useCallback, useEffect, useState, type ReactNode } from "react"
import { useParams, useRouter, useSearchParams } from "next/navigation"
import { ArrowLeft, Building2, CheckCircle2, Copy, Edit3, Loader2, Power, RefreshCcw, Shield, Trash2, UserCog, UserPlus, Users, X, XCircle } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { supabaseBrowser } from "@/lib/supabase/client"

type Overview = { establishment_id: string; establishment_name: string; establishment_code: string; establishment_status: "active" | "inactive"; students_count: number; staff_count: number; classes_count: number; admins_count: number; plan_name: string | null; subscription_status: "active" | "expired" | "suspended" | null; starts_at: string | null; ends_at: string | null; max_students: number | null; max_staff: number | null; max_classes: number | null; max_admins: number | null }
type Member = { member_id: string; user_id: string; role: string; active: boolean; first_name: string | null; last_name: string | null; phone: string | null; avatar_url: string | null; email: string | null }
const roleLabels: Record<string, string> = { owner: "Super administrateur", admin: "Administrateur", administrator: "Administrateur", direction: "Direction", teacher: "Enseignant", accountant: "Comptable", staff: "Personnel" }

export default function Page() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const searchParams = useSearchParams()
  const [overview, setOverview] = useState<Overview | null>(null); const [members, setMembers] = useState<Member[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState(false); const [editing, setEditing] = useState(searchParams.get("action") === "edit"); const [deleteConfirm, setDeleteConfirm] = useState(searchParams.get("action") === "delete"); const [adminModal, setAdminModal] = useState(searchParams.get("action") === "admin"); const [name, setName] = useState(""); const [error, setError] = useState<string | null>(null)
  const [adminForm, setAdminForm] = useState({ first_name: "", last_name: "", email: "", password: "" }); const [adminSaving, setAdminSaving] = useState(false); const [credentials, setCredentials] = useState<{ email: string; password: string } | null>(null)

  const load = useCallback(async () => { setLoading(true); setError(null); const [o, m] = await Promise.all([supabaseBrowser.rpc("platform_admin_establishment_overview", { p_establishment_id: id }), supabaseBrowser.rpc("get_establishment_members", { p_establishment_id: id })]); if (o.error) setError(o.error.message); const row = (o.data?.[0] ?? null) as Overview | null; setOverview(row); setName(row?.establishment_name ?? ""); setMembers((m.data ?? []) as Member[]); if (m.error && !o.error) setError(m.error.message); setLoading(false) }, [id])
  useEffect(() => { void load() }, [load])

  const updateName = async () => { if (!name.trim() || name.trim() === overview?.establishment_name) { setEditing(false); return } setSaving(true); setError(null); const { error: e } = await supabaseBrowser.rpc("platform_admin_update_establishment", { p_establishment_id: id, p_name: name.trim() }); if (e) setError(e.message); else setEditing(false); setSaving(false); await load() }
  const toggleStatus = async () => { if (!overview) return; setSaving(true); setError(null); const { error: e } = await supabaseBrowser.rpc("set_establishment_status", { p_establishment_id: id, p_status: overview.establishment_status === "active" ? "inactive" : "active" }); if (e) setError(e.message); setSaving(false); await load() }
  const changeMemberRole = async (memberId: string, role: string) => { setError(null); const { error: e } = await supabaseBrowser.rpc("update_establishment_member_role", { p_member_id: memberId, p_role: role, p_active: true }); if (e) setError(e.message); await load() }
  const toggleMemberActive = async (member: Member) => { setError(null); const { error: e } = await supabaseBrowser.rpc("platform_admin_set_member_active", { p_member_id: member.member_id, p_active: !member.active }); if (e) setError(e.message); await load() }
  const removeMember = async (member: Member) => { if (member.role === "owner") return; if (!window.confirm(`Retirer ${member.first_name ?? "cet utilisateur"} de l'établissement ?`)) return; setError(null); const { error: e } = await supabaseBrowser.rpc("remove_establishment_member", { p_member_id: member.member_id }); if (e) setError(e.message); await load() }
  const deleteEstablishment = async () => { setDeleting(true); setError(null); const { error: e } = await supabaseBrowser.rpc("platform_admin_delete_establishment", { p_establishment_id: id }); if (e) { setError(e.message); setDeleting(false); setDeleteConfirm(false); return } router.replace("/admin/etablissements") }
  const createSuperAdmin = async () => { setAdminSaving(true); setError(null); setCredentials(null); const { data, error: e } = await supabaseBrowser.functions.invoke("create-establishment-super-admin", { body: { establishment_id: id, ...adminForm } }); if (e) { setError(e.message); setAdminSaving(false); return } if (data?.error) { setError(data.error); setAdminSaving(false); return } setCredentials({ email: data.email, password: data.temporary_password }); setAdminForm({ first_name: "", last_name: "", email: "", password: "" }); await load(); setAdminSaving(false) }

  if (loading) return <div className="mx-auto flex min-h-[50vh] max-w-7xl items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>
  if (!overview) return <div className="mx-auto max-w-3xl space-y-4"><Button variant="ghost" onClick={() => router.push("/admin/etablissements")}><ArrowLeft className="mr-2 h-4 w-4" />Retour</Button><Card><CardContent className="p-8 text-center"><XCircle className="mx-auto mb-3 h-10 w-10 text-destructive" /><p className="font-semibold">Établissement introuvable</p><p className="mt-1 text-sm text-muted-foreground">Vous n'avez peut-être pas les droits nécessaires.</p></CardContent></Card></div>
  const initials = overview.establishment_name.split(" ").map(p => p[0]).join("").slice(0, 2).toUpperCase()

  return <div className="mx-auto max-w-7xl space-y-6 pb-10">
    <div className="flex flex-wrap items-center justify-between gap-3"><Button variant="ghost" onClick={() => router.push("/admin/etablissements")}><ArrowLeft className="mr-2 h-4 w-4" />Établissements</Button><div className="flex gap-2"><Button variant="outline" onClick={() => void load()}><RefreshCcw className="mr-2 h-4 w-4" />Actualiser</Button><Button variant="outline" onClick={() => setAdminModal(true)}><UserPlus className="mr-2 h-4 w-4" />Créer le super administrateur</Button><Button variant="destructive" onClick={() => setDeleteConfirm(true)}><Trash2 className="mr-2 h-4 w-4" />Supprimer</Button></div></div>
    {error && <div className="rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}
    <Card className="overflow-hidden"><div className="border-b bg-primary/[0.04] p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-primary text-lg font-bold text-primary-foreground">{initials || <Building2 className="h-6 w-6" />}</div><div><div className="flex flex-wrap items-center gap-2">{editing ? <div className="flex flex-wrap items-center gap-2"><Input value={name} onChange={e => setName(e.target.value)} className="max-w-sm" autoFocus /><Button size="sm" onClick={updateName} disabled={saving}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : "Enregistrer"}</Button><Button size="sm" variant="ghost" onClick={() => { setName(overview.establishment_name); setEditing(false) }}>Annuler</Button></div> : <><h1 className="text-2xl font-bold tracking-tight">{overview.establishment_name}</h1><Button size="icon" variant="ghost" onClick={() => setEditing(true)} aria-label="Modifier le nom"><Edit3 className="h-4 w-4" /></Button></>}</div><p className="mt-1 font-mono text-sm text-muted-foreground">{overview.establishment_code}</p><div className="mt-3 flex flex-wrap items-center gap-2 text-sm"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 font-medium ${overview.establishment_status === "active" ? "bg-emerald-100 text-emerald-700" : "bg-muted text-muted-foreground"}`}>{overview.establishment_status === "active" ? <CheckCircle2 className="h-3.5 w-3.5" /> : <XCircle className="h-3.5 w-3.5" />}{overview.establishment_status === "active" ? "Actif" : "Suspendu"}</span>{overview.plan_name && <span className="rounded-full bg-background px-2.5 py-1 text-muted-foreground">Plan : {overview.plan_name}</span>}</div></div></div><Button variant={overview.establishment_status === "active" ? "destructive" : "default"} onClick={toggleStatus} disabled={saving}>{overview.establishment_status === "active" ? <Power className="mr-2 h-4 w-4" /> : <RefreshCcw className="mr-2 h-4 w-4" />}{overview.establishment_status === "active" ? "Suspendre" : "Réactiver"}</Button></div></div>
      <CardContent className="grid gap-4 p-6 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<Users className="h-4 w-4" />} label="Élèves" value={overview.students_count} limit={overview.max_students} /><Stat icon={<UserCog className="h-4 w-4" />} label="Personnel" value={overview.staff_count} limit={overview.max_staff} /><Stat icon={<Building2 className="h-4 w-4" />} label="Classes" value={overview.classes_count} limit={overview.max_classes} /><Stat icon={<Shield className="h-4 w-4" />} label="Administrateurs" value={overview.admins_count} limit={overview.max_admins} /></CardContent></Card>
    <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Comptes utilisateurs</CardTitle><p className="mt-1 text-sm text-muted-foreground">Tous les comptes pouvant se connecter à cet établissement.</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-medium">{members.length} comptes</span><Button size="sm" onClick={() => setAdminModal(true)}><UserPlus className="mr-2 h-4 w-4" />Créer le super administrateur</Button></div></div></CardHeader><CardContent className="p-0">{members.length === 0 ? <div className="p-8 text-center"><Users className="mx-auto mb-3 h-9 w-9 text-muted-foreground" /><p className="font-medium">Aucun compte utilisateur</p><p className="mt-1 text-sm text-muted-foreground">Créez le premier compte, celui-ci sera le super administrateur de l'établissement.</p><Button className="mt-4" onClick={() => setAdminModal(true)}><UserPlus className="mr-2 h-4 w-4" />Créer le super administrateur</Button></div> : <div className="divide-y">{members.map(member => <div key={member.member_id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-semibold">{`${member.first_name?.[0] ?? ""}${member.last_name?.[0] ?? ""}`.toUpperCase() || "U"}</div><div className="min-w-0"><p className="truncate font-medium">{[member.first_name, member.last_name].filter(Boolean).join(" ") || "Utilisateur"}</p><p className="truncate text-xs text-muted-foreground">{member.email || "E-mail non disponible"}</p><p className="text-xs text-muted-foreground">{member.phone || "Aucun téléphone"}</p></div></div><div className="flex flex-wrap items-center justify-end gap-2"><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-medium">{roleLabels[member.role] ?? member.role}</span><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${member.active ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700"}`}>{member.active ? "Actif" : "Désactivé"}</span><Button size="sm" variant={member.active ? "outline" : "default"} onClick={() => void toggleMemberActive(member)}>{member.active ? "Désactiver" : "Réactiver"}</Button>{member.role !== "owner" && <Button size="icon" variant="ghost" className="text-destructive hover:text-destructive" onClick={() => void removeMember(member)} aria-label="Retirer"><Trash2 className="h-4 w-4" /></Button>}</div></div>)}</div>}</CardContent></Card>
      <div className="space-y-6"><Card><CardHeader><CardTitle>Abonnement</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Row label="Statut" value={overview.subscription_status ? ({ active: "Actif", expired: "Expiré", suspended: "Suspendu" } as Record<string, string>)[overview.subscription_status] : "Non configuré"} /><Row label="Plan" value={overview.plan_name || "—"} /><Row label="Début" value={overview.starts_at ? new Date(overview.starts_at).toLocaleDateString("fr-FR") : "—"} /><Row label="Fin" value={overview.ends_at ? new Date(overview.ends_at).toLocaleDateString("fr-FR") : "—"} /><Button className="mt-2 w-full" variant="outline" onClick={() => router.push(`/admin/abonnements?establishment=${id}`)}>Gérer l'abonnement</Button></CardContent></Card><Card className="border-destructive/30"><CardHeader><CardTitle className="text-destructive">Zone dangereuse</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">La suppression est définitive et supprime les données rattachées à l'établissement.</p><Button variant="destructive" className="w-full" onClick={() => setDeleteConfirm(true)}><Trash2 className="mr-2 h-4 w-4" />Supprimer l'établissement</Button></CardContent></Card></div></div>

    {adminModal && <Modal title="Créer le super administrateur" onClose={() => { if (!adminSaving) setAdminModal(false) }}><p className="mb-5 text-sm text-muted-foreground">Ce compte sera rattaché exclusivement à <strong>{overview.establishment_name}</strong> et recevra le rôle Super administrateur.</p>{credentials ? <div className="space-y-4"><div className="rounded-lg border bg-muted/40 p-4"><p className="text-sm font-medium">Compte créé avec succès</p><div className="mt-3 space-y-2 text-sm"><Credential label="E-mail" value={credentials.email} /><Credential label="Mot de passe" value={credentials.password} /></div></div><p className="text-xs text-muted-foreground">Conservez ces identifiants de manière sécurisée. Le mot de passe n'est affiché ici qu'après la création.</p><Button className="w-full" onClick={() => setAdminModal(false)}>Terminer</Button></div> : <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Prénom" value={adminForm.first_name} onChange={v => setAdminForm(f => ({ ...f, first_name: v }))} /><Field label="Nom" value={adminForm.last_name} onChange={v => setAdminForm(f => ({ ...f, last_name: v }))} /></div><Field label="E-mail de connexion" type="email" value={adminForm.email} onChange={v => setAdminForm(f => ({ ...f, email: v }))} /><Field label="Mot de passe" type="password" placeholder="Laisser vide pour générer automatiquement" value={adminForm.password} onChange={v => setAdminForm(f => ({ ...f, password: v }))} /><Button className="w-full" onClick={() => void createSuperAdmin()} disabled={adminSaving || !adminForm.first_name.trim() || !adminForm.last_name.trim() || !adminForm.email.trim()}>{adminSaving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <UserPlus className="mr-2 h-4 w-4" />}Créer le compte</Button></div>}</Modal>}
    {deleteConfirm && <Modal title="Supprimer cet établissement ?" onClose={() => setDeleteConfirm(false)}><p className="text-sm text-muted-foreground">Cette action est irréversible. Toutes les données rattachées à <strong>{overview.establishment_name}</strong> seront supprimées.</p><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setDeleteConfirm(false)} disabled={deleting}>Annuler</Button><Button variant="destructive" onClick={() => void deleteEstablishment()} disabled={deleting}>{deleting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Trash2 className="mr-2 h-4 w-4" />}Supprimer définitivement</Button></div></Modal>}
  </div>
}

function Stat({ icon, label, value, limit }: { icon: ReactNode; label: string; value: number; limit: number | null }) { return <div className="rounded-xl border p-4"><div className="flex items-center gap-2 text-sm text-muted-foreground">{icon}{label}</div><p className="mt-2 text-2xl font-bold">{value}{limit != null && <span className="text-sm font-normal text-muted-foreground"> / {limit}</span>}</p></div> }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 border-b py-2 last:border-0"><span className="text-muted-foreground">{label}</span><span className="font-medium">{value}</span></div> }
function Field({ label, value, onChange, type = "text", placeholder = "" }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <label className="block space-y-1.5"><span className="text-sm font-medium">{label}</span><Input type={type} value={value} placeholder={placeholder} onChange={e => onChange(e.target.value)} /></label> }
function Credential({ label, value }: { label: string; value: string }) { const copy = () => void navigator.clipboard?.writeText(value); return <div className="flex items-center justify-between gap-3 rounded-md border bg-background px-3 py-2"><div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className="truncate font-mono">{value}</p></div><Button size="icon" variant="ghost" onClick={copy} aria-label={`Copier ${label}`}><Copy className="h-4 w-4" /></Button></div> }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onMouseDown={e => { if (e.target === e.currentTarget) onClose() }}><Card className="w-full max-w-lg"><CardHeader className="flex flex-row items-center justify-between"><CardTitle>{title}</CardTitle><Button size="icon" variant="ghost" onClick={onClose} aria-label="Fermer"><X className="h-4 w-4" /></Button></CardHeader><CardContent>{children}</CardContent></Card></div> }
