"use client"

import { useEffect, useState } from "react"
import { LifeBuoy, Loader2, Send } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { useAuthentification } from "@/providers/authentification.provider"
import { supabaseBrowser } from "@/lib/supabase/client"

export default function Page(){const {contexte}=useAuthentification();const establishmentId=contexte?.establishments?.[0]?.id;const [subject,setSubject]=useState("");const [message,setMessage]=useState("");const [sending,setSending]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState("");useEffect(()=>{setDone(false)},[establishmentId]);const send=async()=>{if(!establishmentId||!subject.trim()||!message.trim())return;setSending(true);setError("");const {error}=await supabaseBrowser.rpc("create_support_request",{p_establishment_id:establishmentId,p_subject:subject.trim(),p_message:message.trim(),p_priority:"normal"});if(error)setError(error.message);else{setSubject("");setMessage("");setDone(true)}setSending(false)};return <div className="mx-auto max-w-3xl space-y-6"><div><p className="text-sm font-medium text-terre">Assistance</p><h1 className="text-3xl font-bold">Service technique</h1><p className="mt-1 text-pierre">Un problème avec l'application ? Contactez l'équipe NOVA.</p></div><Card><CardHeader><CardTitle className="flex items-center gap-2"><LifeBuoy className="h-5 w-5"/>Nouvelle demande</CardTitle></CardHeader><CardContent className="space-y-4">{error&&<div className="rounded-lg border border-rouge-terre/30 bg-rouge-terre/5 p-3 text-sm text-rouge-terre">{error}</div>}{done&&<div className="rounded-lg border border-terre/20 bg-terre-soft/40 p-3 text-sm text-terre">Votre demande a bien été transmise au service technique.</div>}<Input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Sujet"/><textarea value={message} onChange={e=>setMessage(e.target.value)} className="min-h-40 w-full rounded-md border bg-background p-3 text-sm" placeholder="Décrivez votre problème…"/><Button onClick={()=>void send()} disabled={sending||!establishmentId||!subject.trim()||!message.trim()}>{sending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Send className="mr-2 h-4 w-4"/>}Envoyer au service technique</Button></CardContent></Card></div>}
