"use client"
import { useEffect, useState } from "react"
import { AlertTriangle, CalendarDays, GraduationCap, Save, Users, School, ShieldCheck } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { supabaseBrowser } from "@/lib/supabase/client"

type School = { id:string; name:string; code:string; status:"active"|"inactive" }
type Sub = { establishment_id:string; plan_name:string; starts_at:string; ends_at:string; status:"active"|"expired"|"suspended"; notes:string|null; max_students:number|null; max_staff:number|null; max_classes:number|null; max_admins:number|null }
type Overview = { students_count:number; staff_count:number; classes_count:number; admins_count:number; establishment_name:string; establishment_code:string; establishment_status:string; plan_name:string|null; subscription_status:string|null; starts_at:string|null; ends_at:string|null; max_students:number|null; max_staff:number|null; max_classes:number|null; max_admins:number|null }

const emptyForm={plan_name:"Manuel",starts_at:new Date().toISOString().slice(0,10),ends_at:"",status:"active",max_students:"",max_staff:"",max_classes:"",max_admins:"",notes:""}

export default function Page(){
 const [schools,setSchools]=useState<School[]>([]); const [subs,setSubs]=useState<Sub[]>([]); const [selected,setSelected]=useState(""); const [overview,setOverview]=useState<Overview|null>(null); const [form,setForm]=useState(emptyForm); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 const load=async()=>{const [{data:a},{data:b}]=await Promise.all([supabaseBrowser.from("establishments").select("id,name,code,status").order("name"),supabaseBrowser.from("establishment_subscriptions").select("*")]);setSchools(a||[]);setSubs(b||[])}
 useEffect(()=>{load()},[])
 const choose=async(id:string)=>{setSelected(id);setMessage(""); const {data,error}=await supabaseBrowser.rpc("platform_admin_establishment_overview",{p_establishment_id:id}); if(error){setMessage(error.message);return} const o=Array.isArray(data)?data[0]:data; setOverview(o||null); const s=subs.find(x=>x.establishment_id===id); if(s)setForm({plan_name:s.plan_name,starts_at:s.starts_at,ends_at:s.ends_at,status:s.status,max_students:s.max_students?.toString()||"",max_staff:s.max_staff?.toString()||"",max_classes:s.max_classes?.toString()||"",max_admins:s.max_admins?.toString()||"",notes:s.notes||""}); else setForm(emptyForm)}
 const save=async()=>{if(!selected||!form.ends_at){setMessage("Sélectionnez un établissement et une date de fin.");return} setSaving(true);setMessage(""); const toInt=(v:string)=>v.trim()?Number(v):null; const {error}=await supabaseBrowser.rpc("platform_admin_set_subscription",{p_establishment_id:selected,p_plan_name:form.plan_name,p_starts_at:form.starts_at,p_ends_at:form.ends_at,p_status:form.status,p_max_students:toInt(form.max_students),p_max_staff:toInt(form.max_staff),p_max_classes:toInt(form.max_classes),p_max_admins:toInt(form.max_admins),p_notes:form.notes||null}); setSaving(false); setMessage(error?error.message:"Abonnement et limites enregistrés."); if(!error){await load();await choose(selected)}}
 const daysLeft=overview?.ends_at?Math.ceil((new Date(overview.ends_at).getTime()-Date.now())/86400000):null
 const quota=(current:number,limit:number|null)=>limit?`${current} / ${limit}`:`${current} / ∞`
 return <div className="mx-auto max-w-7xl space-y-6">
  <div><p className="text-sm font-medium text-primary">Gestion commerciale</p><h1 className="text-3xl font-bold">Abonnements & contrôle des établissements</h1><p className="mt-1 text-muted-foreground">Activez une période, définissez les limites et surveillez l'utilisation réelle.</p></div>
  <div className="grid gap-6 lg:grid-cols-[minmax(240px,0.8fr)_minmax(0,1.5fr)]">
   <Card><CardHeader><CardTitle className="text-base">Établissements</CardTitle></CardHeader><CardContent className="space-y-2">{schools.map(s=>{const sub=subs.find(x=>x.establishment_id===s.id);return <button key={s.id} onClick={()=>choose(s.id)} className={"w-full rounded-xl border p-4 text-left transition "+(selected===s.id?"border-primary bg-primary/5":"hover:bg-muted/50")}><div className="flex items-start justify-between gap-3"><p className="font-medium">{s.name}</p><span className={"rounded-full px-2 py-0.5 text-[11px] "+(s.status==="active"?"bg-emerald-100 text-emerald-700":"bg-muted text-muted-foreground")}>{s.status==="active"?"Actif":"Inactif"}</span></div><div className="mt-1 flex justify-between text-xs text-muted-foreground"><span>{s.code}</span><span>{sub?sub.status:"Non configuré"}</span></div></button>})}</CardContent></Card>
   <div className="space-y-6">
    {overview&&<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={GraduationCap} label="Élèves" value={quota(overview.students_count,overview.max_students)}/><Stat icon={Users} label="Personnel" value={quota(overview.staff_count,overview.max_staff)}/><Stat icon={School} label="Classes / salles" value={quota(overview.classes_count,overview.max_classes)}/><Stat icon={ShieldCheck} label="Administrateurs" value={quota(overview.admins_count,overview.max_admins)}/></div>}
    {overview&&daysLeft!==null&&<div className={"flex items-center gap-3 rounded-xl border p-4 "+(daysLeft<=30?"border-amber-200 bg-amber-50":"border-primary/10 bg-primary/[0.04]")}><AlertTriangle className="h-5 w-5 shrink-0"/><div><p className="text-sm font-semibold">{daysLeft<0?"Abonnement expiré":daysLeft===0?"Expiration aujourd'hui":`Expiration dans ${daysLeft} jour${daysLeft>1?"s":""}`}</p><p className="text-xs text-muted-foreground">Fin prévue le {new Date(overview.ends_at).toLocaleDateString("fr-FR")}. Une alerte est générée automatiquement dans les 30 derniers jours.</p></div></div>}
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="h-5 w-5"/>Configurer l'abonnement</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label>Plan</Label><Input value={form.plan_name} onChange={e=>setForm({...form,plan_name:e.target.value})}/></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Date de début" type="date" value={form.starts_at} onChange={v=>setForm({...form,starts_at:v})}/><Field label="Date de fin" type="date" value={form.ends_at} onChange={v=>setForm({...form,ends_at:v})}/></div><div className="space-y-2"><Label>Statut</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.status} onChange={e=>setForm({...form,status:e.target.value as any})}><option value="active">Actif</option><option value="suspended">Suspendu</option><option value="expired">Expiré</option></select></div>
     <div className="rounded-xl border border-primary/10 bg-primary/[0.03] p-4"><div className="mb-3"><p className="font-semibold">Limites du plan</p><p className="text-xs text-muted-foreground">Laissez vide pour ne pas imposer de limite.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre max. d'élèves" value={form.max_students} onChange={v=>setForm({...form,max_students:v})}/><Field label="Nombre max. de personnel" value={form.max_staff} onChange={v=>setForm({...form,max_staff:v})}/><Field label="Nombre max. de classes / salles" value={form.max_classes} onChange={v=>setForm({...form,max_classes:v})}/><Field label="Nombre max. d'administrateurs" value={form.max_admins} onChange={v=>setForm({...form,max_admins:v})}/></div></div>
     <div className="space-y-2"><Label>Note interne</Label><Input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Optionnel"/></div>{message&&<p className="text-sm text-muted-foreground">{message}</p>}<Button disabled={saving||!selected} onClick={save} className="w-full"><Save className="mr-2 h-4 w-4"/>{saving?"Enregistrement…":"Enregistrer l'abonnement"}</Button>
    </CardContent></Card>
   </div>
  </div>
 </div>
}
function Field({label,value,onChange,type="number"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <div className="space-y-2"><Label>{label}</Label><Input type={type} min={type==="number"?1:undefined} value={value} onChange={e=>onChange(e.target.value)}/></div>}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <Card><CardContent className="flex items-center gap-3 p-4"><div className="rounded-lg bg-primary/10 p-2 text-primary"><Icon className="h-4 w-4"/></div><div><p className="text-xs text-muted-foreground">{label}</p><p className="font-semibold">{value}</p></div></CardContent></Card>}
