"use client"
import { useEffect,useState } from "react"
import { CalendarDays, Save } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { supabaseBrowser } from "@/lib/supabase/client"
type School={id:string;name:string;code:string};type Sub={establishment_id:string;plan_name:string;starts_at:string;ends_at:string;status:"active"|"expired"|"suspended";notes:string|null}
export default function Page(){const [schools,setSchools]=useState<School[]>([]);const [subs,setSubs]=useState<Sub[]>([]);const [selected,setSelected]=useState("");const [form,setForm]=useState({plan_name:"Manuel",starts_at:new Date().toISOString().slice(0,10),ends_at:"",status:"active",notes:""});const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
useEffect(()=>{(async()=>{const [{data:a},{data:b}]=await Promise.all([supabaseBrowser.from("establishments").select("id,name,code").order("name"),supabaseBrowser.from("establishment_subscriptions").select("*")]);setSchools(a||[]);setSubs(b||[])})()},[]);
const choose=(id:string)=>{setSelected(id);const s=subs.find(x=>x.establishment_id===id);if(s)setForm({plan_name:s.plan_name,starts_at:s.starts_at,ends_at:s.ends_at,status:s.status,notes:s.notes||""})};
const save=async()=>{if(!selected||!form.ends_at)return setMessage("Sélectionnez un établissement et une date de fin.");setSaving(true);setMessage("");const {error}=await supabaseBrowser.rpc("set_establishment_subscription",{p_establishment_id:selected,p_plan_name:form.plan_name,p_starts_at:form.starts_at,p_ends_at:form.ends_at,p_status:form.status,p_notes:form.notes||null});setSaving(false);setMessage(error?error.message:"Abonnement enregistré.");if(!error){const {data}=await supabaseBrowser.from("establishment_subscriptions").select("*");setSubs(data||[])}};
return <div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm font-medium text-primary">Gestion commerciale</p><h1 className="text-3xl font-bold">Abonnements</h1><p className="mt-1 text-muted-foreground">Gestion manuelle et sécurisée des périodes d'accès.</p></div><div className="grid gap-6 lg:grid-cols-[1fr_1.4fr]"><Card><CardHeader><CardTitle className="text-base">Établissements</CardTitle></CardHeader><CardContent className="space-y-2">{schools.map(s=>{const sub=subs.find(x=>x.establishment_id===s.id);return <button key={s.id} onClick={()=>choose(s.id)} className={"w-full rounded-xl border p-4 text-left transition "+(selected===s.id?"border-primary bg-primary/5":"hover:bg-muted/50")}><p className="font-medium">{s.name}</p><div className="mt-1 flex justify-between text-xs text-muted-foreground"><span>{s.code}</span><span>{sub?sub.status:"Non configuré"}</span></div></button>})}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="h-5 w-5"/>Configurer l'abonnement</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label>Plan</Label><Input value={form.plan_name} onChange={e=>setForm({...form,plan_name:e.target.value})}/></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Début</Label><Input type="date" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></div><div className="space-y-2"><Label>Fin</Label><Input type="date" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></div></div><div className="space-y-2"><Label>Statut</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.status} onChange={e=>setForm({...form,status:e.target.value as any})}><option value="active">Actif</option><option value="suspended">Suspendu</option><option value="expired">Expiré</option></select></div><div className="space-y-2"><Label>Note interne</Label><Input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Optionnel"/></div>{message&&<p className="text-sm text-muted-foreground">{message}</p>}<Button disabled={saving||!selected} onClick={save} className="w-full"><Save className="mr-2 h-4 w-4"/>Enregistrer</Button></CardContent></Card></div></div>}