"use client"

import { useMemo, useState } from "react"
import { useSearchParams } from "next/navigation"
import { CreditCard, Receipt, Wallet } from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { useParentPortal } from "@/hooks/use-parent-portal"

const METHODS:Record<string,string>={especes:"Espèces",cheque:"Chèque",virement:"Virement",mobile:"Mobile Money",mobile_money:"Mobile Money"}
const money=(n:number)=>new Intl.NumberFormat("fr-FR").format(n)+" FCFA"
export default function ParentsPaiementsPage(){
 const params=useSearchParams();const {loading,error,children,payments}=useParentPortal();const [id,setId]=useState(params.get("eleve")||"tous")
 const allowed=children.filter(c=>c.can_view_finance);const ids=id==="tous"?allowed.map(c=>c.id):[id];const list=payments.filter(p=>{const c=children.find(x=>x.enrollment_id===p.enrollment_id);return c?ids.includes(c.id):false});const paid=list.reduce((s,p)=>s+p.amount,0)
 if(loading)return <div className="flex min-h-[50vh] items-center justify-center text-pierre">Chargement des paiements...</div>
 return <div className="space-y-6"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-terre"><CreditCard className="h-6 w-6"/>Paiements</h1><p className="text-pierre">Historique réel des paiements de scolarité</p></div>{error&&<Card className="border-red-200 bg-red-50"><CardContent className="p-4 text-red-700">{error}</CardContent></Card>}<Select value={id} onValueChange={setId}><SelectTrigger className="w-[240px]"><SelectValue placeholder="Filtrer par enfant"/></SelectTrigger><SelectContent><SelectItem value="tous">Tous les enfants</SelectItem>{allowed.map(c=><SelectItem key={c.id} value={c.id}>{c.first_name} {c.last_name}</SelectItem>)}</SelectContent></Select><div className="grid gap-4 sm:grid-cols-2"><Card><CardContent className="flex items-center gap-3 p-5"><Wallet className="h-5 w-5 text-terre"/><div><p className="text-xs uppercase text-pierre">Total enregistré</p><p className="text-xl font-bold text-terre">{money(paid)}</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-5"><Receipt className="h-5 w-5 text-emerald-700"/><div><p className="text-xs uppercase text-pierre">Opérations</p><p className="text-xl font-bold text-terre">{list.length}</p></div></CardContent></Card></div><Card><CardHeader><CardTitle className="text-base">Historique</CardTitle><CardDescription>{list.length} paiement(s)</CardDescription></CardHeader><CardContent className="space-y-3">{list.length===0?<p className="py-8 text-center text-pierre">Aucun paiement enregistré.</p>:list.map(p=>{const c=children.find(x=>x.enrollment_id===p.enrollment_id);return <div key={p.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-terre/10 p-4"><div><p className="font-medium text-terre">{c?`${c.first_name} ${c.last_name}`:"Paiement"}</p><p className="text-sm text-pierre">{new Date(p.payment_date).toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"})}{p.method?` · ${METHODS[p.method]??p.method}`:""}</p>{p.reference&&<Badge variant="outline" className="mt-1">Réf. {p.reference}</Badge>}</div><p className="text-lg font-bold text-emerald-700">+ {money(p.amount)}</p></div>})}</CardContent></Card></div>
}