"use client"

import { useEffect, useMemo, useState } from "react"
import { ArrowLeft, CheckCircle2, Loader2, Save, Search } from "lucide-react"
import { useParams, useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { useAuthentification } from "@/providers/authentification.provider"
import { enseignantPortalService, type TeacherAssessment, type TeacherAssessmentStudent } from "@/services/enseignant-portal.service"

export default function NotesEnseignantPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter()
  const { utilisateur, contexte, estEnCoursDeChargement } = useAuthentification()
  const [assessments, setAssessments] = useState<TeacherAssessment[]>([]); const [selected, setSelected] = useState<TeacherAssessment | null>(null)
  const [students, setStudents] = useState<TeacherAssessmentStudent[]>([]); const [scores, setScores] = useState<Record<string, string>>({}); const [comments, setComments] = useState<Record<string, string>>({}); const [search, setSearch] = useState("")
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null)
  const establishment = contexte?.establishments?.find((item) => item.id === id)

  useEffect(() => { if (!estEnCoursDeChargement && (!utilisateur || utilisateur.role !== "enseignant" || !establishment)) router.replace("/enseignant") }, [estEnCoursDeChargement, utilisateur, establishment, router])
  useEffect(() => { if (!establishment || !id) return; setLoading(true); enseignantPortalService.getAssessments(id).then(setAssessments).catch((e) => setMessage(e instanceof Error ? e.message : "Impossible de charger les évaluations.")).finally(() => setLoading(false)) }, [id, establishment])

  const openAssessment = async (assessment: TeacherAssessment) => { setSelected(assessment); setMessage(null); setSearch(""); try { const rows = await enseignantPortalService.getAssessmentStudents(assessment.assessment_id); setStudents(rows); setScores(Object.fromEntries(rows.map((r) => [r.student_id, r.score == null ? "" : String(r.score)]))); setComments(Object.fromEntries(rows.map((r) => [r.student_id, r.comment ?? ""]))) } catch (e) { setMessage(e instanceof Error ? e.message : "Impossible de charger les élèves.") } }
  const filteredStudents = useMemo(() => { const q = search.trim().toLowerCase(); if (!q) return students; return students.filter((s) => `${s.last_name} ${s.first_name} ${s.student_number ?? ""}`.toLowerCase().includes(q)) }, [students, search])
  const completed = students.filter((s) => scores[s.student_id]?.trim() !== "").length
  const save = async (student: TeacherAssessmentStudent) => { if (!selected) return; const raw = scores[student.student_id]?.replace(",", ".").trim(); const score = Number(raw); if (!raw || !Number.isFinite(score) || score < 0 || score > selected.max_score) { setMessage(`La note doit être comprise entre 0 et ${selected.max_score}.`); return }; setSaving(student.student_id); setMessage(null); try { await enseignantPortalService.recordGrade(selected.assessment_id, student.student_id, score, comments[student.student_id]); setStudents((current) => current.map((r) => r.student_id === student.student_id ? { ...r, score, comment: comments[student.student_id] || null } : r)); if (student.score == null) setAssessments((current) => current.map((r) => r.assessment_id === selected.assessment_id ? { ...r, grade_count: r.grade_count + 1 } : r)); setMessage(`Note de ${student.last_name} ${student.first_name} enregistrée.`) } catch (e) { setMessage(e instanceof Error ? e.message : "Enregistrement impossible.") } finally { setSaving(null) } }

  if (estEnCoursDeChargement || !utilisateur || !establishment) return <main className="min-h-screen bg-creme flex items-center justify-center"><Loader2 className="h-5 w-5 animate-spin" /></main>
  return <main className="min-h-screen bg-creme"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8">
    <header className="mb-6"><Button variant="ghost" size="sm" onClick={() => router.push(`/enseignant/etablissement/${id}`)}><ArrowLeft className="mr-2 h-4 w-4" />Retour à mon espace</Button><div className="mt-3"><p className="text-xs font-medium uppercase tracking-wide text-terre">Évaluation</p><h1 className="text-2xl font-semibold">Saisie des notes</h1><p className="text-sm text-muted-foreground">{establishment.name} · vos évaluations uniquement</p></div></header>
    {message && <div role="status" className="mb-5 rounded-lg border bg-white p-3 text-sm">{message}</div>}
    {!selected ? <Card><CardHeader><CardTitle className="text-base">Choisissez une évaluation</CardTitle></CardHeader><CardContent>{loading ? <div className="flex justify-center p-10"><Loader2 className="h-5 w-5 animate-spin" /></div> : assessments.length === 0 ? <p className="p-8 text-center text-sm text-muted-foreground">Aucune évaluation disponible.</p> : <div className="divide-y">{assessments.map((a) => <button key={a.assessment_id} type="button" onClick={() => void openAssessment(a)} className="flex w-full items-center justify-between gap-4 rounded-md px-3 py-4 text-left hover:bg-muted/40 focus-visible:outline-none focus-visible:ring-2"><div className="min-w-0"><p className="font-medium">{a.title}</p><p className="truncate text-sm text-muted-foreground">{a.class_name} · {a.subject_name} · {a.term ?? "Période non précisée"}</p></div><div className="shrink-0 text-right text-sm"><p>{a.assessment_date}</p><p className="text-muted-foreground">{a.grade_count} note(s) saisie(s)</p></div></button>)}</div>}</CardContent></Card> : <div>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">{selected.title}</h2><p className="text-sm text-muted-foreground">{selected.class_name} · {selected.subject_name} · note sur {selected.max_score}</p></div><Button variant="outline" onClick={() => setSelected(null)}>Changer d’évaluation</Button></div>
      <Card className="mb-5"><CardContent className="flex flex-wrap items-center justify-between gap-4 p-4"><div className="flex items-center gap-3"><div className="rounded-full bg-muted p-2"><CheckCircle2 className="h-4 w-4" /></div><div><p className="text-sm font-medium">Progression de la saisie</p><p className="text-xs text-muted-foreground">{completed} sur {students.length} élève(s) renseigné(s)</p></div></div><div className="h-2 w-full max-w-xs overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-terre transition-all" style={{ width: `${students.length ? Math.round(completed / students.length * 100) : 0}%` }} /></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input aria-label="Rechercher un élève" className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Rechercher un élève…" /></div></CardContent></Card>
      <Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-b bg-muted/30 text-left text-muted-foreground"><tr><th className="px-5 py-3">Élève</th><th className="px-5 py-3">Note / {selected.max_score}</th><th className="px-5 py-3">Commentaire</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y">{filteredStudents.map((s) => <tr key={s.student_id}><td className="px-5 py-3 font-medium">{s.last_name} {s.first_name}<span className="ml-2 text-xs font-normal text-muted-foreground">{s.student_number ?? ""}</span></td><td className="w-36 px-5 py-3"><Input inputMode="decimal" aria-label={`Note de ${s.last_name} ${s.first_name}`} value={scores[s.student_id] ?? ""} onChange={(e) => setScores((c) => ({ ...c, [s.student_id]: e.target.value }))} /></td><td className="px-5 py-3"><Input value={comments[s.student_id] ?? ""} onChange={(e) => setComments((c) => ({ ...c, [s.student_id]: e.target.value }))} placeholder="Facultatif" /></td><td className="px-5 py-3 text-right"><Button size="sm" onClick={() => void save(s)} disabled={saving === s.student_id}>{saving === s.student_id ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}{saving === s.student_id ? "Enregistrement…" : "Enregistrer"}</Button></td></tr>)}</tbody></table></div>{filteredStudents.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">{search ? "Aucun élève trouvé." : "Aucun élève inscrit à cette évaluation."}</p>}</CardContent></Card>
    </div>}
  </div></main>
}
