-- Fix state-funded student imports: use the tuition schedule generated by the enrollment trigger,
-- apply the establishment's payer settings to that schedule, and avoid duplicate option schedules.

create or replace function public.import_state_students(
  p_establishment_id uuid,
  p_academic_year_id uuid,
  p_class_id uuid,
  p_tuition_plan_id uuid,
  p_students jsonb,
  p_option_ids uuid[] default '{}',
  p_caution_amount numeric default 0,
  p_caution_refundable boolean default true
) returns jsonb
language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare
  row_data jsonb;
  v_student_id uuid;
  v_enrollment_id uuid;
  v_plan public.tuition_plans%rowtype;
  v_class public.school_classes%rowtype;
  v_settings public.establishment_finance_settings%rowtype;
  v_option public.student_options%rowtype;
  v_total_state numeric;
  v_total_parent numeric;
  v_count integer := 0;
  v_failed integer := 0;
  v_errors jsonb := '[]'::jsonb;
  v_row_number integer := 0;
begin
  if not private.has_permission(p_establishment_id,'students.manage')
     or not private.has_permission(p_establishment_id,'enrollments.manage') then
    raise exception 'Permission refusee';
  end if;
  if jsonb_typeof(p_students) <> 'array' or jsonb_array_length(p_students)=0 then
    raise exception 'Aucun eleve a importer';
  end if;
  select * into v_settings from public.establishment_finance_settings where establishment_id=p_establishment_id;
  if not coalesce(v_settings.state_students_enabled,false) then
    raise exception 'La prise en charge des eleves de l''Etat n''est pas activee';
  end if;
  if not exists(select 1 from public.academic_years ay where ay.id=p_academic_year_id and ay.establishment_id=p_establishment_id and ay.status='active') then
    raise exception 'L''annee scolaire selectionnee n''est pas active';
  end if;
  select * into v_class from public.school_classes where id=p_class_id and establishment_id=p_establishment_id and active=true;
  if v_class.id is null then raise exception 'Classe invalide'; end if;
  select * into v_plan from public.tuition_plans
  where id=p_tuition_plan_id and establishment_id=p_establishment_id and academic_year_id=p_academic_year_id
    and grade_level_id=v_class.grade_level_id and active=true;
  if v_plan.id is null then raise exception 'Forfait tarifaire invalide'; end if;
  if p_caution_amount < 0 then raise exception 'Caution invalide'; end if;
  if p_caution_amount > 0 and not coalesce(v_settings.state_allows_caution,false) then
    raise exception 'La caution n''est pas autorisee pour les eleves de l''Etat';
  end if;
  if coalesce(array_length(p_option_ids,1),0)>0 and not coalesce(v_settings.state_allows_family_options,true) then
    raise exception 'Les options a la charge des familles ne sont pas autorisees pour les eleves de l''Etat';
  end if;

  for row_data in select value from jsonb_array_elements(p_students) loop
    v_row_number := v_row_number + 1;
    begin
      if nullif(trim(coalesce(row_data->>'first_name','')),'') is null
         or nullif(trim(coalesce(row_data->>'last_name','')),'') is null then
        raise exception 'Nom et prenom obligatoires';
      end if;
      if exists(
        select 1 from public.students s
        where s.establishment_id=p_establishment_id
          and lower(s.last_name)=lower(trim(row_data->>'last_name'))
          and lower(s.first_name)=lower(trim(row_data->>'first_name'))
          and coalesce(s.birth_date::text,'')=coalesce(nullif(trim(row_data->>'birth_date'),''),coalesce(s.birth_date::text,''))
      ) then raise exception 'Eleve deja present'; end if;

      insert into public.students(establishment_id,student_number,last_name,first_name,birth_date,sex,phone,email,active)
      values(p_establishment_id,nullif(trim(row_data->>'student_number'),''),trim(row_data->>'last_name'),trim(row_data->>'first_name'),
        nullif(trim(row_data->>'birth_date'),'')::date,nullif(trim(row_data->>'sex'),''),nullif(trim(row_data->>'phone'),''),
        nullif(trim(row_data->>'email'),''),true)
      returning id into v_student_id;

      -- The enrollment trigger creates the configured tuition schedule once.
      insert into public.enrollments(establishment_id,student_id,academic_year_id,class_id,tuition_plan_id,enrollment_date,status,funding_source,state_expected_amount,parent_payable_amount)
      values(p_establishment_id,v_student_id,p_academic_year_id,p_class_id,p_tuition_plan_id,current_date,'active','state',0,0)
      returning id into v_enrollment_id;

      update public.payment_schedules
      set payer_type=case when coalesce(v_settings.state_covers_tuition,true) then 'state' else 'family' end
      where enrollment_id=v_enrollment_id and category='tuition';

      if coalesce(v_plan.registration_fee,0)>0 then
        insert into public.payment_schedules(enrollment_id,installment_number,label,due_date,amount_due,payer_type,category,priority_rank)
        values(v_enrollment_id,1,'Frais d''inscription',current_date,v_plan.registration_fee,
          case when coalesce(v_settings.state_covers_registration,true) then 'state' else 'family' end,'registration',0);
      end if;

      if coalesce(array_length(p_option_ids,1),0)>0 then
        for v_option in
          select * from public.student_options
          where establishment_id=p_establishment_id and id=any(p_option_ids) and active=true
        loop
          insert into public.enrollment_options(establishment_id,enrollment_id,option_id,amount)
          values(p_establishment_id,v_enrollment_id,v_option.id,coalesce(v_option.default_amount,0));
          -- trg_enrollment_option_schedule creates one family-paid schedule for each option.
        end loop;
        if (select count(*) from public.enrollment_options eo where eo.enrollment_id=v_enrollment_id)<>array_length(p_option_ids,1) then
          raise exception 'Une ou plusieurs options sont invalides';
        end if;
      end if;

      if p_caution_amount>0 then
        insert into public.payment_schedules(enrollment_id,installment_number,label,due_date,amount_due,payer_type,category,is_refundable)
        values(v_enrollment_id,999,'Caution',current_date,p_caution_amount,'family','caution',p_caution_refundable);
      end if;

      select coalesce(sum(ps.amount_due) filter(where ps.payer_type='state'),0),
             coalesce(sum(greatest(ps.amount_due-ps.amount_paid,0)) filter(where ps.payer_type='family'),0)
      into v_total_state,v_total_parent
      from public.payment_schedules ps where ps.enrollment_id=v_enrollment_id;
      update public.enrollments set state_expected_amount=v_total_state,parent_payable_amount=v_total_parent where id=v_enrollment_id;
      v_count:=v_count+1;
    exception when others then
      v_failed:=v_failed+1;
      v_errors:=v_errors||jsonb_build_array(jsonb_build_object('row',v_row_number,'message',sqlerrm,
        'first_name',row_data->>'first_name','last_name',row_data->>'last_name'));
    end;
  end loop;
  return jsonb_build_object('imported',v_count,'failed',v_failed,'errors',v_errors);
end $$;
revoke all on function public.import_state_students(uuid,uuid,uuid,uuid,jsonb,uuid[],numeric,boolean) from public;
grant execute on function public.import_state_students(uuid,uuid,uuid,uuid,jsonb,uuid[],numeric,boolean) to authenticated;
