"use client"

import { useMemo } from "react"
import { Calendar, MapPin, Clock } from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { useParentPortal } from "@/hooks/use-parent-portal"

const TYPES:Record<string,{label:string;className:string}>={reunion:{label:"Réunion",className:"bg-terre-soft text-terre"},examen:{label:"Examen",className:"bg-rose-100 text-rose-700"},fete:{label:"Fête",className:"bg-fuchsia-100 text-fuchsia-700"},conference:{label:"Conférence",className:"bg-sky-100 text-sky-700"},sport:{label:"Sport",className:"bg-emerald-100 text-emerald-700"}}
export default function ParentsEvenementsPage(){const {loading,error,events}=useParentPortal();const lists=useMemo(()=>{const now=Date.now();return {upcoming:events.filter(e=>new Date(e.starts_at).getTime()>=now),past:events.filter(e=>new Date(e.starts_at).getTime()<now)}},[events]);if(loading)return <div className="flex min-h-[50vh] items-center justify-center text-pierre">Chargement des événements...</div>;const render=(items:typeof events)=><div className="space-y-3">{items.map(e=>{const t=TYPES[e.event_type]??{label:e.event_type,className:"bg-slate-100 text-slate-700"};const d=new Date(e.starts_at);return <Card key={e.id}><CardContent className="flex gap-4 p-5"><div className="flex h-14 w-14 shrink-0 flex-col items-center justify-center rounded-xl bg-terre-soft text-terre"><span className="text-[10px] font-semibold uppercase">{d.toLocaleDateString("fr-FR",{month:"short"})}</span><span className="text-xl font-bold">{d.getDate()}</span></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-terre">{e.title}</h3><Badge className={t.className}>{t.label}</Badge></div>{e.description&&<p className="mt-1 text-sm text-pierre">{e.description}</p>}<div className="mt-2 flex flex-wrap gap-3 text-xs text-pierre"><span className="flex items-center gap-1"><Clock className="h-3.5 w-3.5"/>{d.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})}</span>{e.location&&<span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>{e.location}</span>}</div></div></CardContent></Card>})}</div>;return <div className="space-y-8"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-terre"><Calendar className="h-6 w-6"/>Événements</h1><p className="text-pierre">Calendrier scolaire réel de vos établissements</p></div>{error&&<Card className="border-red-200 bg-red-50"><CardContent className="p-4 text-red-700">{error}</CardContent></Card>}<section><h2 className="mb-3 text-sm font-semibold uppercase text-pierre">À venir ({lists.upcoming.length})</h2>{lists.upcoming.length?render(lists.upcoming):<p className="py-8 text-center text-pierre">Aucun événement à venir.</p>}</section>{lists.past.length>0&&<section><h2 className="mb-3 text-sm font-semibold uppercase text-pierre">Passés ({lists.past.length})</h2>{render(lists.past)}</section>}</div>}
