"use client"
import Link from "next/link"
import { useEffect,useMemo,useState } from "react"
import { Building2, Plus, Search, MoreHorizontal } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card,CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { supabaseBrowser } from "@/lib/supabase/client"
type School={id:string;name:string;code:string|null;status:string;created_at:string}
export default function Page(){const [schools,setSchools]=useState<School[]>([]);const [q,setQ]=useState("");const [loading,setLoading]=useState(true);useEffect(()=>{(async()=>{const {data}=await supabaseBrowser.from("establishments").select("id,name,code,status,created_at").order("created_at",{ascending:false});setSchools(data||[]);setLoading(false)})()},[]);const list=useMemo(()=>schools.filter(s=>(s.name+(s.code||"")).toLowerCase().includes(q.toLowerCase())),[schools,q]);return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">Gestion multi-établissements</p><h1 className="text-3xl font-bold">Établissements</h1><p className="mt-1 text-muted-foreground">Créez et administrez les établissements.</p></div><Button asChild><Link href="/admin/etablissements/nouveau"><Plus className="mr-2 h-4 w-4"/>Nouvel établissement</Link></Button></div><div className="relative max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Rechercher…" value={q} onChange={e=>setQ(e.target.value)}/></div><Card><CardContent className="p-0">{loading?<p className="p-10 text-center">Chargement…</p>:list.length===0?<div className="p-12 text-center"><Building2 className="mx-auto mb-3 h-10 w-10 text-muted-foreground"/><p>Aucun établissement</p></div>:list.map(s=><Link href={"/admin/etablissements/"+s.id} key={s.id} className="flex items-center justify-between border-b p-5 hover:bg-muted/50"><div><p className="font-semibold">{s.name}</p><p className="font-mono text-sm text-muted-foreground">{s.code||"—"}</p></div><div className="flex items-center gap-4"><span className="rounded-full bg-muted px-3 py-1 text-xs">{s.status==="active"?"Actif":"Inactif"}</span><MoreHorizontal className="h-5 w-5"/></div></Link>)}</CardContent></Card></div>}